### ISSUE TITLE
cannot use to edit an existing markdown

### ISSUE THREAD

**Issue by ohpax** [kunall17/react-native-markdown-editor#2]
There is no property to pass text to component, therefore; there is no ability to edit an existing markdown

**Comment by JeremyBradshaw7** [comment]
Yeah that's a showstopper for me too, if true

**Comment by kunall17** [comment]
Fixed via https://github.com/kunall17/react-native-markdown-editor/commit/c29b3811da18b0bde3078975712d2464887dd60d Deployed in the npm as well, thanks for the report! 

Please close the issue once satisfied :)
